### PR TITLE
Fix epub standard problems: Containers must include a mimetype file a…

### PR DESCRIPTION
**Pull request by francisco-sanchez-molina**
…s the first file and the first playOrder value in a document shall be 1

### CODE REVIEW

**Comment by francisco-sanchez-molina** [comment]
Thanks!

**Comment by LastLeaf** [comment]
Thanks for your contribution.

If you would like, I could add you into the "contributor" section in package.json.

**Comment by francisco-sanchez-molina** [comment]
Thanks you so much :+1:, but I have changed only two lines, it's not necessary ;)

PD: sorry for my english :)

**Comment by LastLeaf** [comment]
Published on NPM as v1.0.1.

My English is not good either :)

**Pull request merged**
